name: build

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: "11"

      - name: cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: build
        run: |
          chmod +x mvnw
          ./mvnw -B verify --file pom.xml