name: release

on:
  push:
    branches: [main]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.event.head_commit.message, '[release]') }}

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup java 11 x64
        uses: actions/setup-java@v1.4.3
        with:
          java-version: "11"

      - name: cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: build
        run: |
          chmod +x mvnw
          ./mvnw -B verify --file pom.xml

      - name: setup maven central for java11 x64
        uses: actions/setup-java@v1.4.3
        with:
          java-version: "11"
          server-id: central
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          server-password: MAVEN_PASSWORD
          server-username: MAVEN_USERNAME

      - name: release
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: |
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"
          chmod +x mvnw
          ./mvnw -B -X --file pom.xml release:prepare release:perform -Drepository.url=https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git